// <auto-generated />
using System;
using Comjustinspicer.CMS.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Comjustinspicer.CMS.Migrations.ContentZone
{
    [DbContext(typeof(ContentZoneContext))]
    partial class ContentZoneContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Comjustinspicer.CMS.Data.Models.ContentZoneAssignmentDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentZoneId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentPageMasterId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentZoneId")
                        .HasColumnType("uuid");

                    b.Property<string>("SlotName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ContentZoneId");

                    b.HasIndex("ParentPageMasterId", "SlotName")
                        .IsUnique()
                        .HasDatabaseName("IX_ContentZoneAssignments_PageSlot")
                        .HasFilter("\"ParentPageMasterId\" IS NOT NULL");

                    b.HasIndex("ParentZoneId", "SlotName")
                        .IsUnique()
                        .HasDatabaseName("IX_ContentZoneAssignments_ZoneSlot")
                        .HasFilter("\"ParentZoneId\" IS NOT NULL");

                    b.ToTable("ContentZoneAssignments", null, t =>
                        {
                            t.HasCheckConstraint("CK_ContentZoneAssignments_OneParent", "(\"ParentPageMasterId\" IS NOT NULL AND \"ParentZoneId\" IS NULL) OR (\"ParentPageMasterId\" IS NULL AND \"ParentZoneId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Comjustinspicer.CMS.Data.Models.ContentZoneDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ParentMasterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PublicationEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentMasterId")
                        .HasDatabaseName("IX_ContentZones_ParentMasterId");

                    b.ToTable("ContentZones", (string)null);
                });

            modelBuilder.Entity("Comjustinspicer.CMS.Data.Models.ContentZoneItemDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ComponentPropertiesJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("ContentZoneId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentMasterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PublicationEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentMasterId")
                        .HasDatabaseName("IX_ContentZoneItems_ParentMasterId");

                    b.HasIndex("ContentZoneId", "Ordinal");

                    b.ToTable("ContentZoneItems", (string)null);
                });

            modelBuilder.Entity("Comjustinspicer.CMS.Data.Models.ContentZoneAssignmentDTO", b =>
                {
                    b.HasOne("Comjustinspicer.CMS.Data.Models.ContentZoneDTO", "ContentZone")
                        .WithMany()
                        .HasForeignKey("ContentZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comjustinspicer.CMS.Data.Models.ContentZoneDTO", "ParentZone")
                        .WithMany()
                        .HasForeignKey("ParentZoneId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ContentZone");

                    b.Navigation("ParentZone");
                });

            modelBuilder.Entity("Comjustinspicer.CMS.Data.Models.ContentZoneDTO", b =>
                {
                    b.OwnsMany("Comjustinspicer.CMS.Data.Models.CustomField", "CustomFields", b1 =>
                        {
                            b1.Property<Guid>("ContentZoneDTOId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<Guid>("CreatedBy");

                            b1.Property<DateTime>("CreationDate");

                            b1.Property<string>("FieldName")
                                .IsRequired();

                            b1.Property<Guid>("Id");

                            b1.Property<bool>("IsArchived");

                            b1.Property<bool>("IsDeleted");

                            b1.Property<bool>("IsHidden");

                            b1.Property<bool>("IsPublished");

                            b1.Property<Guid>("LastModifiedBy");

                            b1.Property<Guid>("MasterId");

                            b1.Property<DateTime>("ModificationDate");

                            b1.Property<Guid?>("ParentMasterId");

                            b1.Property<DateTime>("PublicationDate");

                            b1.Property<DateTime?>("PublicationEndDate");

                            b1.Property<string>("Slug")
                                .IsRequired();

                            b1.Property<string>("Title")
                                .IsRequired();

                            b1.Property<string>("TypeName")
                                .IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.Property<int>("Version");

                            b1.HasKey("ContentZoneDTOId", "__synthesizedOrdinal");

                            b1.ToTable("ContentZones");

                            b1.ToJson("CustomFields");

                            b1.WithOwner()
                                .HasForeignKey("ContentZoneDTOId");
                        });

                    b.Navigation("CustomFields");
                });

            modelBuilder.Entity("Comjustinspicer.CMS.Data.Models.ContentZoneItemDTO", b =>
                {
                    b.HasOne("Comjustinspicer.CMS.Data.Models.ContentZoneDTO", "ContentZone")
                        .WithMany("Items")
                        .HasForeignKey("ContentZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Comjustinspicer.CMS.Data.Models.CustomField", "CustomFields", b1 =>
                        {
                            b1.Property<Guid>("ContentZoneItemDTOId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<Guid>("CreatedBy");

                            b1.Property<DateTime>("CreationDate");

                            b1.Property<string>("FieldName")
                                .IsRequired();

                            b1.Property<Guid>("Id");

                            b1.Property<bool>("IsArchived");

                            b1.Property<bool>("IsDeleted");

                            b1.Property<bool>("IsHidden");

                            b1.Property<bool>("IsPublished");

                            b1.Property<Guid>("LastModifiedBy");

                            b1.Property<Guid>("MasterId");

                            b1.Property<DateTime>("ModificationDate");

                            b1.Property<Guid?>("ParentMasterId");

                            b1.Property<DateTime>("PublicationDate");

                            b1.Property<DateTime?>("PublicationEndDate");

                            b1.Property<string>("Slug")
                                .IsRequired();

                            b1.Property<string>("Title")
                                .IsRequired();

                            b1.Property<string>("TypeName")
                                .IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.Property<int>("Version");

                            b1.HasKey("ContentZoneItemDTOId", "__synthesizedOrdinal");

                            b1.ToTable("ContentZoneItems");

                            b1.ToJson("CustomFields");

                            b1.WithOwner()
                                .HasForeignKey("ContentZoneItemDTOId");
                        });

                    b.Navigation("ContentZone");

                    b.Navigation("CustomFields");
                });

            modelBuilder.Entity("Comjustinspicer.CMS.Data.Models.ContentZoneDTO", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
