// <auto-generated />
using System;
using Comjustinspicer.CMS.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Comjustinspicer.CMS.Migrations.Article
{
    [DbContext(typeof(ArticleContext))]
    partial class ArticleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Comjustinspicer.CMS.Data.Models.ArticleDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArticleListMasterId")
                        .HasColumnType("uuid")
                        .HasColumnName("ArticleListMasterId");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PublicationEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArticleListMasterId");

                    b.ToTable("Articles", (string)null);
                });

            modelBuilder.Entity("Comjustinspicer.CMS.Data.Models.ArticleListDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PublicationEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ArticleLists");
                });

            modelBuilder.Entity("Comjustinspicer.CMS.Data.Models.ArticleDTO", b =>
                {
                    b.OwnsMany("Comjustinspicer.CMS.Data.Models.CustomField", "CustomFields", b1 =>
                        {
                            b1.Property<Guid>("ArticleDTOId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<Guid>("CreatedBy");

                            b1.Property<DateTime>("CreationDate");

                            b1.Property<string>("FieldName")
                                .IsRequired();

                            b1.Property<Guid>("Id");

                            b1.Property<bool>("IsArchived");

                            b1.Property<bool>("IsDeleted");

                            b1.Property<bool>("IsHidden");

                            b1.Property<bool>("IsPublished");

                            b1.Property<Guid>("LastModifiedBy");

                            b1.Property<Guid>("MasterId");

                            b1.Property<DateTime>("ModificationDate");

                            b1.Property<DateTime>("PublicationDate");

                            b1.Property<DateTime?>("PublicationEndDate");

                            b1.Property<string>("Slug")
                                .IsRequired();

                            b1.Property<string>("Title")
                                .IsRequired();

                            b1.Property<string>("TypeName")
                                .IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.Property<int>("Version");

                            b1.HasKey("ArticleDTOId", "__synthesizedOrdinal");

                            b1.ToTable("Articles");

                            b1.ToJson("CustomFields");

                            b1.WithOwner()
                                .HasForeignKey("ArticleDTOId");
                        });

                    b.Navigation("CustomFields");
                });

            modelBuilder.Entity("Comjustinspicer.CMS.Data.Models.ArticleListDTO", b =>
                {
                    b.OwnsMany("Comjustinspicer.CMS.Data.Models.CustomField", "CustomFields", b1 =>
                        {
                            b1.Property<Guid>("ArticleListDTOId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<Guid>("CreatedBy");

                            b1.Property<DateTime>("CreationDate");

                            b1.Property<string>("FieldName")
                                .IsRequired();

                            b1.Property<Guid>("Id");

                            b1.Property<bool>("IsArchived");

                            b1.Property<bool>("IsDeleted");

                            b1.Property<bool>("IsHidden");

                            b1.Property<bool>("IsPublished");

                            b1.Property<Guid>("LastModifiedBy");

                            b1.Property<Guid>("MasterId");

                            b1.Property<DateTime>("ModificationDate");

                            b1.Property<DateTime>("PublicationDate");

                            b1.Property<DateTime?>("PublicationEndDate");

                            b1.Property<string>("Slug")
                                .IsRequired();

                            b1.Property<string>("Title")
                                .IsRequired();

                            b1.Property<string>("TypeName")
                                .IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.Property<int>("Version");

                            b1.HasKey("ArticleListDTOId", "__synthesizedOrdinal");

                            b1.ToTable("ArticleLists");

                            b1.ToJson("CustomFields");

                            b1.WithOwner()
                                .HasForeignKey("ArticleListDTOId");
                        });

                    b.Navigation("CustomFields");
                });
#pragma warning restore 612, 618
        }
    }
}
