// // <auto-generated />
// using System;
// using Microsoft.EntityFrameworkCore;
// using Microsoft.EntityFrameworkCore.Infrastructure;
// using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
// using comjustinspicer.Data;

// #nullable disable

// namespace comjustinspicer.Migrations
// {
//     [DbContext(typeof(BlogContext))]
//     partial class BlogContextModelSnapshot : ModelSnapshot
//     {
//         protected override void BuildModel(ModelBuilder modelBuilder)
//         {
// #pragma warning disable 612, 618
//             modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

//             modelBuilder.Entity("comjustinspicer.Data.Models.Blog.Post", b =>
//                 {
//                     b.Property<Guid>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("TEXT");

//                     b.Property<string>("Title")
//                         .IsRequired()
//                         .HasColumnType("TEXT");

//                     b.HasKey("Id");

//                     b.ToTable("Posts");
//                 });
// #pragma warning restore 612, 618
//         }
//     }
// }
